### ISSUE TITLE
Custom rewrites with variables/parameters

### ISSUE THREAD

**Issue by RazinShaikh** [Quantomatic/zxlive#108]
Support defining and applying custom rewrites that have variables in them. A simple example is shown below.

![image](https://github.com/Quantomatic/zxlive/assets/28257517/a0fa9951-d50f-4861-bf0a-334ac5ec5966)

**Comment by jvdwetering** [comment]
This is getting dangerously close to Quantomatic complexity ;)
The problem is that if you want to apply this rule in reverse that there are then infinite possibilities that match.
You can probably restrict to a very small subset that might still be useful: every spider on the LHS has a unique variable appearing in it, and you can't apply the rewrite in reverse.

**Comment by RazinShaikh** [comment]
It does not even need to be a unique variable. We simply want to avoid multiple variables on the same spider in the LHS.

**Comment by RazinShaikh** [comment]
Implemented in #185
