### ISSUE TITLE
Zooming and panning

### ISSUE THREAD

**Issue by jvdwetering** [Quantomatic/zxlive#44]
Currently there is no way to zoom in and out, and there is also no way to pan the screen.
Probably we want to have a dedicated tool for panning, as well as a keyboard shortcut, like spacebar+dragging to pan and control+scroll to zoom.

**Comment by akissinger** [comment]
Current zoom behaviour is a bit crazy. It zooms on scroll without pressing control, its very sensitive (a tiny flick on my touchpad turns everything into a speck), and zoom in/out don't act like each other's inverses. This is not too bad with a mouse, but it's very annoying on my laptop, because the touchpad often accidentally scrolls a bit when you try to click.

**Comment by y-richie-y** [comment]
I have the same problem too, I had to disable it to use the tool on laptop.

**Comment by jvdwetering** [comment]
The latest commit should fix this. At least on my end it is a lot more gradual now. We can probably still tweak the exact values a bit.

**Comment by jvdwetering** [comment]
This is now implemented as of the QPL23 hackathon.
